"""
OpenClaw Email Notification System

Provides daily email summaries and alerts for the OpenClaw system.
Integrates with the existing coordinator to send:
- Daily morning briefings
- High-stakes bet alerts
- Circuit breaker status changes
- Budget warnings
- Performance summaries

Configuration via environment variables:
- OPENCLAW_EMAIL_SMTP_SERVER
- OPENCLAW_EMAIL_SMTP_PORT (default: 587)
- OPENCLAW_EMAIL_USERNAME
- OPENCLAW_EMAIL_PASSWORD
- OPENCLAW_EMAIL_RECIPIENT
- OPENCLAW_EMAIL_ENABLED (default: false)
"""

import json
import logging
import os
import smtplib
import ssl
from datetime import datetime, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger("openclaw.email")

DATA_DIR = Path(__file__).resolve().parents[2] / "data"
CACHE_DIR = DATA_DIR / "cache"
CACHE_DIR.mkdir(parents=True, exist_ok=True)


class OpenClawEmailNotifier:
    """Email notification system for OpenClaw."""
    
    def __init__(self):
        self.enabled = os.getenv("OPENCLAW_EMAIL_ENABLED", "false").lower() == "true"
        self.smtp_server = os.getenv("OPENCLAW_EMAIL_SMTP_SERVER", "")
        self.smtp_port = int(os.getenv("OPENCLAW_EMAIL_SMTP_PORT", "587"))
        self.username = os.getenv("OPENCLAW_EMAIL_USERNAME", "")
        self.password = os.getenv("OPENCLAW_EMAIL_PASSWORD", "")
        self.recipient = os.getenv("OPENCLAW_EMAIL_RECIPIENT", "")
        
        if self.enabled and not all([self.smtp_server, self.username, self.password, self.recipient]):
            logger.warning("Email enabled but missing configuration. Disabling.")
            self.enabled = False
    
    def _send_email(self, subject: str, html_body: str, text_body: str) -> bool:
        """Send email via SMTP."""
        if not self.enabled:
            logger.debug("Email disabled, logging to file instead")
            self._log_to_file(subject, text_body)
            return False
        
        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = self.username
            msg["To"] = self.recipient
            
            msg.attach(MIMEText(text_body, "plain"))
            msg.attach(MIMEText(html_body, "html"))
            
            context = ssl.create_default_context()
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls(context=context)
                server.login(self.username, self.password)
                server.sendmail(self.username, self.recipient, msg.as_string())
            
            logger.info(f"Email sent: {subject}")
            return True
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            self._log_to_file(subject, text_body)
            return False
    
    def _log_to_file(self, subject: str, body: str):
        """Fallback: log to file if email fails or disabled."""
        log_file = CACHE_DIR / f"email_notifications_{datetime.now().strftime('%Y-%m')}.log"
        with open(log_file, "a") as f:
            f.write(f"\n{'='*60}\n")
            f.write(f"Date: {datetime.now().isoformat()}\n")
            f.write(f"Subject: {subject}\n")
            f.write(f"{'='*60}\n")
            f.write(body)
            f.write("\n")
    
    def send_daily_briefing(self, stats: Dict) -> bool:
        """Send daily morning briefing email."""
        today = datetime.now().strftime("%Y-%m-%d")
        subject = f"OpenClaw Daily Briefing - {today}"
        
        text_body = f"""
OpenClaw Daily Briefing - {today}
{'='*50}

CIRCUIT BREAKER STATUS: {stats.get('circuit_breaker', 'UNKNOWN')}
DAILY COST: ${stats.get('daily_cost_usd', 0):.2f}
BUDGET REMAINING: {stats.get('budget_remaining_pct', 0):.0f}%

TASKS PROCESSED (24h):
- Total: {stats.get('tasks_24h', 0)}
- Local (qwen2.5:3b): {stats.get('tasks_local', 0)}
- Kimi Escalations: {stats.get('tasks_kimi', 0)}

AVERAGE LATENCY:
- Local: {stats.get('latency_local_ms', 0):.0f}ms
- Kimi: {stats.get('latency_kimi_ms', 0):.0f}ms

NOTABLE EVENTS:
{chr(10).join(stats.get('events', ['- No significant events']))}

---
Generated by OpenClaw v2.1
"""
        
        html_body = f"""
<html>
<head>
<style>
    body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
    h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
    h2 {{ color: #34495e; margin-top: 25px; }}
    .metric {{ background: #ecf0f1; padding: 15px; margin: 10px 0; border-radius: 5px; }}
    .metric-label {{ font-weight: bold; color: #7f8c8d; }}
    .metric-value {{ font-size: 1.2em; color: #2c3e50; }}
    .status-closed {{ color: #27ae60; font-weight: bold; }}
    .status-open {{ color: #e74c3c; font-weight: bold; }}
    .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #bdc3c7; font-size: 0.9em; color: #7f8c8d; }}
</style>
</head>
<body>
    <h1>OpenClaw Daily Briefing</h1>
    <p style="color: #7f8c8d;">{today}</p>
    
    <h2>System Status</h2>
    <div class="metric">
        <span class="metric-label">Circuit Breaker:</span>
        <span class="metric-value {'status-closed' if stats.get('circuit_breaker') == 'CLOSED' else 'status-open'}">
            {stats.get('circuit_breaker', 'UNKNOWN')}
        </span>
    </div>
    <div class="metric">
        <span class="metric-label">Daily Cost:</span>
        <span class="metric-value">${stats.get('daily_cost_usd', 0):.2f}</span>
    </div>
    <div class="metric">
        <span class="metric-label">Budget Remaining:</span>
        <span class="metric-value">{stats.get('budget_remaining_pct', 0):.0f}%</span>
    </div>
    
    <h2>Activity (Last 24 Hours)</h2>
    <div class="metric">
        <span class="metric-label">Tasks Processed:</span>
        <span class="metric-value">{stats.get('tasks_24h', 0)}</span><br>
        <small>Local (qwen2.5:3b): {stats.get('tasks_local', 0)} | Kimi Escalations: {stats.get('tasks_kimi', 0)}</small>
    </div>
    
    <h2>Performance</h2>
    <div class="metric">
        <span class="metric-label">Average Latency:</span><br>
        Local: {stats.get('latency_local_ms', 0):.0f}ms | Kimi: {stats.get('latency_kimi_ms', 0):.0f}ms
    </div>
    
    <h2>Notable Events</h2>
    <ul>
        {''.join(f'<li>{e}</li>' for e in stats.get('events', ['No significant events']))}
    </ul>
    
    <div class="footer">
        Generated by OpenClaw v2.1<br>
        Coordinator: Kimi CLI (Deep Intelligence Unit)
    </div>
</body>
</html>
"""
        
        return self._send_email(subject, html_body, text_body)
    
    def send_high_stakes_alert(self, game: Dict) -> bool:
        """Send alert for high-stakes bet opportunity."""
        subject = f"HIGH STAKES: {game.get('away_team')} @ {game.get('home_team')}"
        
        text_body = f"""
HIGH-STAKES BET ALERT
{'='*50}

Game: {game.get('away_team')} @ {game.get('home_team')}
Recommended: {game.get('recommendation', 'N/A')}
Edge: {game.get('edge_conservative', 0):.1f}%
Units: {game.get('recommended_units', 0)}

ROUTING: This game was escalated to Kimi CLI for deep analysis.

Context:
- Tournament Round: {game.get('tournament_round', 'N/A')}
- Neutral Site: {game.get('is_neutral', False)}
- Integrity Verdict: {game.get('integrity_verdict', 'N/A')}

Time: {datetime.now().isoformat()}
"""
        
        html_body = f"""
<html>
<body style="font-family: Arial, sans-serif;">
    <h2 style="color: #e74c3c;">HIGH-STAKES BET ALERT</h2>
    <table style="border-collapse: collapse; width: 100%;">
        <tr><td style="padding: 8px; border: 1px solid #ddd;"><strong>Game:</strong></td><td style="padding: 8px; border: 1px solid #ddd;">{game.get('away_team')} @ {game.get('home_team')}</td></tr>
        <tr><td style="padding: 8px; border: 1px solid #ddd;"><strong>Recommendation:</strong></td><td style="padding: 8px; border: 1px solid #ddd;">{game.get('recommendation', 'N/A')}</td></tr>
        <tr><td style="padding: 8px; border: 1px solid #ddd;"><strong>Edge:</strong></td><td style="padding: 8px; border: 1px solid #ddd;">{game.get('edge_conservative', 0):.1f}%</td></tr>
        <tr><td style="padding: 8px; border: 1px solid #ddd;"><strong>Units:</strong></td><td style="padding: 8px; border: 1px solid #ddd;">{game.get('recommended_units', 0)}</td></tr>
    </table>
    <p style="background: #fff3cd; padding: 10px; border-left: 4px solid #ffc107;">
        <strong>ROUTING:</strong> This game was escalated to <strong>Kimi CLI</strong> for deep analysis.
    </p>
</body>
</html>
"""
        
        return self._send_email(subject, html_body, text_body)
    
    def send_circuit_breaker_alert(self, state: str, reason: str) -> bool:
        """Send alert when circuit breaker state changes."""
        subject = f"OpenClaw Circuit Breaker: {state}"
        
        text_body = f"""
CIRCUIT BREAKER STATUS CHANGE
{'='*50}

State: {state}
Reason: {reason}
Time: {datetime.now().isoformat()}

ACTION REQUIRED:
- OPEN: All tasks routing to Kimi (increased cost)
- Check Ollama service status
- Review logs for failure patterns
"""
        
        color = "#e74c3c" if state == "OPEN" else "#27ae60"
        html_body = f"""
<html>
<body style="font-family: Arial, sans-serif;">
    <h2 style="color: {color};">Circuit Breaker: {state}</h2>
    <p><strong>Reason:</strong> {reason}</p>
    <p><strong>Time:</strong> {datetime.now().isoformat()}</p>
    
    <div style="background: {'#ffebee' if state == 'OPEN' else '#e8f5e9'}; padding: 15px; margin: 15px 0;">
        <strong>ACTION REQUIRED:</strong><br>
        {"All tasks now routing to Kimi (increased cost). Check Ollama service." if state == "OPEN" else "Circuit closed. Local LLM operational."}
    </div>
</body>
</html>
"""
        
        return self._send_email(subject, html_body, text_body)
    
    def send_budget_warning(self, usage_pct: float) -> bool:
        """Send warning when approaching daily budget."""
        subject = f"OpenClaw Budget Alert: {usage_pct:.0f}% Used"
        
        text_body = f"""
BUDGET WARNING
{'='*50}

Daily Budget Usage: {usage_pct:.0f}%

RECOMMENDATIONS:
- High-stakes routing may be reduced
- Consider adjusting kimi_daily_usd in config
- Review routing rules if this is recurring
"""
        
        html_body = f"""
<html>
<body style="font-family: Arial, sans-serif;">
    <h2 style="color: #f39c12;">Budget Alert: {usage_pct:.0f}% Used</h2>
    
    <div style="background: #fff3cd; padding: 15px; border-left: 4px solid #ffc107;">
        <strong>Recommendations:</strong>
        <ul>
            <li>High-stakes routing may be reduced</li>
            <li>Consider adjusting <code>kimi_daily_usd</code> in config</li>
            <li>Review routing rules if this is recurring</li>
        </ul>
    </div>
</body>
</html>
"""
        
        return self._send_email(subject, html_body, text_body)


# Global instance
_notifier: Optional[OpenClawEmailNotifier] = None


def get_notifier() -> OpenClawEmailNotifier:
    """Get singleton instance of email notifier."""
    global _notifier
    if _notifier is None:
        _notifier = OpenClawEmailNotifier()
    return _notifier


def send_daily_briefing(stats: Dict) -> bool:
    """Convenience function to send daily briefing."""
    return get_notifier().send_daily_briefing(stats)


def send_high_stakes_alert(game: Dict) -> bool:
    """Convenience function to send high-stakes alert."""
    return get_notifier().send_high_stakes_alert(game)


def send_circuit_breaker_alert(state: str, reason: str) -> bool:
    """Convenience function to send circuit breaker alert."""
    return get_notifier().send_circuit_breaker_alert(state, reason)


def send_budget_warning(usage_pct: float) -> bool:
    """Convenience function to send budget warning."""
    return get_notifier().send_budget_warning(usage_pct)


if __name__ == "__main__":
    # Test the email system
    logging.basicConfig(level=logging.INFO)
    
    print("Testing OpenClaw Email Notifier...")
    print(f"Email enabled: {get_notifier().enabled}")
    
    # Send test briefing
    test_stats = {
        'circuit_breaker': 'CLOSED',
        'daily_cost_usd': 0.45,
        'budget_remaining_pct': 91,
        'tasks_24h': 24,
        'tasks_local': 20,
        'tasks_kimi': 4,
        'latency_local_ms': 450,
        'latency_kimi_ms': 3200,
        'events': ['2 high-stakes escalations', '1 VOLATILE verdict resolved']
    }
    
    result = send_daily_briefing(test_stats)
    print(f"Daily briefing sent: {result}")
    print(f"Check {CACHE_DIR} for logged notifications if email disabled")
